sudo: required
language: java
env:
  global:
  - DOCKER_IMAGE=strapdata/elassandra-builder
notifications:
  email: true
services:
- docker
install: true
script:
  - docker run -v ${PWD}:/src ${DOCKER_IMAGE}
deploy:
  provider: releases
  api_key:
    secure: RVesdqBUpXVk38ac2Me3NvuOdEEwOLOZJYhRxafGoYVeCKLewn2Q65FVhVr/Xo7+BgK5fP95oWnjHfaNiA/GYpljqiVnuzngZZlZ3vudU0sa5Sp/Zcb3mRkHRuUogCmD+RU5ioGVBGDQvNg83RVeEoQeim5aDpJV72oTS2cbcTYGiJoNdGv+ReV+h9E89Un+AMB/25Dy3Ji0aLMpyJ5zSbFIOX1hL7pRzFA7PqM8QNFgCz89GkfEVDrcMlz0sHsb/AARZYx6fdLkjqUyWccZSF4WN3ZoQyxFykEE/XU9bejAyLVdg8xxgqJxfq3yKhFKUrA55nEbX0qfOvD/89J1d1MTlpo8m6JZ3FSZJcHoRvGAn7MEyuoOY5NezsOimRRHDyqyulo03phyF3wDVsU3MNGxoDeKGzg7W2w9QsAlDEHxVtj7h1fuatndOgJNqdILMvEE7t+B+dbkJks0CTm4EP6567tiAQ6jznflqHzkUyvih7dwN8OKbRPJifTtVzRrCBpMglEkKc3ll1DmK8aqPELRGT/LfVvMrfq22agXONokkxzVw9empOITiPoSitbnXbHjucUZNdTfpJM3DTmWtGMimIPx7KTMMK3aA3Rt/C1yOptmS3AkuR9o8DLpqbIpp5nXOD0gK0vZcwkUNyuxMnaSFwJ3OJNA9mbQL42NUmk=
  file: distribution/tar/target/releases/elassandra-2.4.2.tar.gz
  on:
    repo: DBarthe/elassandra
